### ISSUE TITLE
疑惑：最终实现V层还是持有P的对象，并不是通过持有接口来通信。

### ISSUE THREAD

**Issue by ningStillIn** [serge66/MVPDemo#1]
public class SingleInterfaceActivity extends BaseMVPActivity<SingleInterfacePresenter>
        implements SingleInterfaceContract.View ｛
...
@Override
    protected SingleInterfacePresenter createPresenter() {
        return new SingleInterfacePresenter();
    }
...
｝
SingleInterfaceActivity 还是通过持有SingleInterfacePresenter的对象来和SingleInterfacePresenter通信的，并没有使用SingleInterfaceContract中SingleInterfacePresenter的接口：
interface Presenter {
        void getData(int curPage);
    }
来和SingleInterfacePresenter进行通信。
这个是为什么，望解惑，谢谢

**Comment by serge66** [comment]
@ningStillIn  哈喽 大兄弟 去看下这个仓库 https://github.com/serge66/MVPAdvanceDemo

**Comment by ningStillIn** [comment]
@serge66 嗯嗯 刚看了一下 很完美。
